name: Push New Markdown Files to dev.to Repo

on:
  push:
    branches: ["master"]
    paths: 
      - '_posts/*.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Pushes to another repository
      uses: cpina/github-action-push-to-another-repository@main
      env:
        SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
      with:
        source-directory: '_posts/'
        destination-github-username: 'kunalworldwide'
        destination-repository-name: 'dev.to-deployment'
        user-email: dev.topublisherbot@github.com
        commit-message: "New post(s) from $GITHUB_REF"
        target-branch: ingestion

    - name: Test get variable exported by push-to-another-repository
      run: echo $DESTINATION_CLONED_DIRECTORY
